#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/gsdb1?characterEncoding=utf8&useSSL=true
#    username: root
#    password: 1qaz2wsx
#
#mybatis:
#  type-aliases-package: com.proschan.gameserver.model
